### PR TITLE
feature/issue-21 Adds sender name to message

### LINKED ISSUE #21: Where to get name of the sender
https://github.com/tawn33y/whatsapp-cloud-api/blob/dd73985e97539dd70f4eb74ee256eef63dda2062/src/startExpressServer.ts#L71

Where on the api can i get the **name** of the sender, When i check the **from key** it only has cellNumber of the sender but no name

bot.on('message', async (msg) => {
      console.log(msg.from.name);  //undefined 
      console.log(msg.from); //+27xxxxxxxxxx
}

### PR DESCRIPTION
**Pull request by guskuma**
This fix #21 

Adds sender name to message. Changes "from" field to object with wa_id (sender number) and name

### CODE REVIEW

**Comment by tawn33y** [comment]
@guskuma I just realized that having the `name` under the `from` object is not the best course of action as it will mean current users will have to change their code from using `from` directly as the phone number/whatsapp id to reading it from `from.wa_id`.

This means that the change will be **breaking**. For breaking changes, I'd prefer slowly decrementing a method/functionality before fully removing it.

Thus, for now, I'd recommend we use something simpler:

```ts
export interface Message {
  from: string;
  // add the name here
  name: string;
  id: string;
  timestamp: string;
  type: PubSubEvent;
  data: FreeFormObject;
}
```

**Comment by guskuma** [comment]
That's OK for me @tawn33y , and that's why I asked before. If it works it's fine for me!

**Comment by tawn33y** [comment]
Yep. Just do the change. I can approve and we can merge it.

**Comment by guskuma** [comment]
@tawn33y change done!

**Comment by RyzorBent** [comment]
@tawn33y i think the change was done to put the name as part of the message object, which makes it a non-breaking change. Unless I'm missing something from @guskuma's change.

**Comment by guskuma** [comment]
Yes, maybe I'm missing something too. I've done changes [this](https://github.com/tawn33y/whatsapp-cloud-api/pull/25/commits/e2efab55db15519f952e33bb1502130b92d3f97b) commit. Please tell me if there's something else I need to do.

**Comment by tawn33y** [comment]
@RyzorBent @guskuma I've tagged you in the comments again. Kindly confirm if you can see them.

**Comment by guskuma** [comment]
Hello @tawn33y , I can't see any comments I was tagged... where can I find it? I didn't receive any e-mail either.

**Review by j05u3 — DISMISSED** [review]
lgtm

[edit] sorry if I am meddling in here lol

**Comment by tawn33y** [comment]
@guskuma @RyzorBent I meant this comment:

image

And this one:

image

**Comment by tawn33y** [comment]
I've made the changes. Approving the PR.

Sorry if we had a break of communication somewhere, but thanks for making the changes! @guskuma @RyzorBent @j05u3  😃

**Review by tawn33y — APPROVED** [review]

**Comment by j05u3** [comment]
> I've made the changes. Approving the PR.
> 
> Sorry if we had a break of communication somewhere, but thanks for making the changes! @guskuma @RyzorBent @j05u3 😃

thanks a lot, can't wait for the next release 🙏

**Comment by tawn33y** [comment]
@j05u3 @guskuma @RyzorBent  This is now live: [https://github.com/tawn33y/whatsapp-cloud-api/releases/tag/v0.2.6](https://github.com/tawn33y/whatsapp-cloud-api/releases/tag/v0.2.6)

Feel free to test & [create a new issue](https://github.com/tawn33y/whatsapp-cloud-api/issues) in case of any issues. Hopefully though, there are none. 😄

**Comment by RyzorBent** [comment]
Brilliant, :) ... will test and feedback.

**Comment by guskuma** [comment]
@tawn33y sorry for miscomunication! I really could not see what was going on (my fault, maybe from my lack of experience here). I'll be more diligent next time! Thank you!

**Comment by tawn33y** [comment]
Hi @guskuma,
Don't worry about it at all! We learn a new thing every day. Feel free to keep contributing to the library, happy to have your contributions 😊

**Pull request merged**
