### PR TITLE
Implemented template quick replies

### LINKED ISSUE #52: Template buttons are not being handled
While it is now possible to handle responses to simple message buttons that we send directly to the user, the same is not possible if we send buttons as part of a WhatsApp template.
This is because templates with buttons have a different JSON structure and different types than a conventional message.

### PR DESCRIPTION
**Pull request by macols77**
Now we can handle the quick reply buttons sent as part of a template.

More info: https://developers.facebook.com/docs/whatsapp/api/messages/message-templates/interactive-message-templates/#callback-from-a-quick-reply-button-click

This fixes #52

### CODE REVIEW

**Comment by tawn33y** [comment]
This looks great! Thanks for your contribution. 😀

Can we create an issue to track this?

**Comment by tawn33y** [comment]
I've made a change that ensures that CI tests run on all PRs: [https://github.com/tawn33y/whatsapp-cloud-api/pull/51](https://github.com/tawn33y/whatsapp-cloud-api/pull/51)

Please pull & merge latest from `main` 😀

**Comment by tawn33y** [comment]
Hi @macols77, light ping on this

**Comment by macols77** [comment]
Sorry @tawn33y, too much work lately and don't know why github notifications weren't showing up.
I think I've done everything you asked, let me know if you need anything else

**Comment by Live4win** [comment]
Are there any news for this? I would also like to see this feature get enabled. Are any more contributions needed?

**Comment by tawn33y** [comment]
Closing - please [read more here](https://github.com/tawn33y/whatsapp-cloud-api/issues/65).

**Pull request closed without merging**
